{"name": "Проверка: авторизация под существующим пользователем", "status": "passed", "description": "Проверяем, что можно авторизоваться под существующим пользователем", "start": 1721331651842, "stop": 1721331651999, "uuid": "a3b92665-c85e-4155-9078-6f6f5b163066", "historyId": "d6d9741e680ce030d18e2c84981fafc0", "testCaseId": "d6d9741e680ce030d18e2c84981fafc0", "fullName": "tests.test_login_user.TestLoginUser#test_login_with_existing_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "Mike"}, {"name": "thread", "value": "7692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}